# Kubernetes deployment description for Identifiers.org Resource Recommender API Service
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1
kind: Deployment
metadata:
    name: resource-recommender
spec:
    selector:
        matchLabels:
            environment: production
            tier: api
            app: resource-recommender
    replicas: 1
    template:
        metadata:
            labels:
                environment: production
                tier: api
                app: resource-recommender
        spec:
            affinity:
              nodeAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 5
                    preference:
                      matchExpressions:
                        - key: node-reliability
                          operator: In
                          values:
                            - stable
              podAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      labelSelector:
                        matchExpressions:
                          - key: environment
                            operator: In
                            values:
                            - production
                          - key: tier
                            operator: In
                            values:
                            - api
                          - key: app
                            operator: In
                            values:
                            - link-checker
                      topologyKey: "kubernetes.io/hostname"
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 10
                    podAffinityTerm:
                      labelSelector:
                        matchExpressions:
                        - key: environment
                          operator: In
                          values:
                          - production
                        - key: tier
                          operator: In
                          values:
                          - api
                        - key: app
                          operator: In
                          values:
                          - resource-recommender
                      topologyKey: "kubernetes.io/hostname"
            containers:
                - name: cloud-ws-resource-recommender
                  image: identifiersorg/cloud-ws-resource-recommender:1.1.1
                  imagePullPolicy: Always
                  resources:
                      requests:
                          memory: 640Mi
                  env:
                  - name: WS_RESOURCE_RECOMMENDER_JVM_MEMORY_MAX
                    value: "512m"
                  - name: WS_RESOURCE_RECOMMENDER_CONFIG_BACKEND_SERVICE_LINK_CHECKER_HOST
                    value: link-checker
                  ports:
                  - containerPort: 8083
