# Kubernetes deployment description for Identifiers.org Link Checker Service
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: link-checker
spec:
    selector:
        matchLabels:
            environment: production
            tier: api
            app: link-checker
    replicas: 1
