# Kubernetes deployment description for Identifiers.org Resource Recommender Web Service
#
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: resource-recommender
spec:
    selector:
        matchLabels:
            environment: production
            tier: api
            app: resource-recommender
    replicas: 1
