# Kubernetes deployment description for Identifiers.org Satellite Web Frontend
#
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: web-frontend
spec:
    selector:
        matchLabels:
            environment: production
            tier: frontend
            app: web-frontend
    replicas: 2
