# identifiers.org docker-compose based cloud deployment

#														#
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>	#
#														#

version: "3"
    metadata:
        image: identifiersorg/cloud-ws-metadata
        environment:
            - WS_METADATA_CONFIG_RESOLVER_HOST=resolver
            - WS_METADATA_CONFIG_RESOLVER_PORT=8080
        ports:
            - 8082:8082
        depends_on:
            - resolver
