# Kubernetes deployment description for backend Redis
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis
spec:
    selector:
        matchLabels:
            environment: production
            tier: backend
            app: redis
    replicas: 1
