# Kubernetes deployment description for Identifiers.org Prefix Registration API Service
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1
kind: Deployment
metadata:
    name: registry
spec:
    selector:
        matchLabels:
            environment: production
            tier: api
            app: registry
