# Kubernetes deployment description for Identifiers.org Compact ID Resolution API Service
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1
kind: Deployment
metadata:
    name: sparql
spec:
    selector:
        matchLabels:
            environment: production
            tier: api
            app: sparql
            deployment: satellite
    replicas: 2
    template:
        metadata:
            labels:
                environment: production
                tier: api
                app: sparql
                deployment: satellite
        spec:
            tolerations:
            - key: "iorg-node-reliability-ephemeral-noschedule"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
            affinity:
              nodeAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 5
                    preference:
                      matchExpressions:
                        - key: iorg-node-reliability
                          operator: In
                          values:
                            - stable
            containers:
                - name: sparql-identifiers
                  image: jerven/sparql-identifiers
                  imagePullPolicy: Always
                  resources:
                      requests:
                          memory: 360Mi
                          cpu: 100m
                  ports:
                  - containerPort: 8080
                  
