# Kubernetes declaration of Identifiers.org Resource Recommender Deployment
#
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: v1
kind: Service
metadata:
    name: resource-recommender
    labels:
        environment: production
        tier: api
        app: resource-recommender
