# redis-ha chart configuration file
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
cluster:
    slaveCount: 3
master:
    resources:
        Memory: 2Gi
        CPU: 1
    persistence:
        enabled: false
    podLabels:
        backend-node: redisha
        redisha-role: master
slave:
    podLabels:
        backend-node: redisha
        redisha-role: slave
