# Identifiers.org satellite platform ingress controller
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: satellite-deployment
    labels:
        environment: production
        tier: api
        app: satellite-deployment
    annotations:
        kubernetes.io/ingress.class: "gce"
        kubernetes.io/ingress.global-static-ip-name: idorg-satellite
        ingress.gcp.kubernetes.io/pre-shared-cert: 'cert-iorg-sat-prod-resolver,cert-iorg-sat-prod-metadata,cert-iorg-sat-prod-web,cert-iorg-sat-prod-web-main2'
        kubernetes.io/ingress.allow-http: "true"
spec:
    rules:
    # Resolver rules
    - host: resolver.api.identifiers.org
      http:
          paths:
              - backend:
                  serviceName: nodeport-resolver
                  servicePort: 8080
    # Metadata Service rules
    - host: metadata.api.identifiers.org
      http:
          paths:
              - backend:
                  serviceName: nodeport-metadata
                  servicePort: 8082
    # Web Frontend rules
    - host: cloud.identifiers.org
      http:
          paths:
              - backend:
                  serviceName: nodeport-web-satellite
                  servicePort: 80
    - host: identifiers.org
      http:
          paths:
              - backend:
                  serviceName: nodeport-web-satellite
                  servicePort: 80
