# Kubernetes deployment description for Identifiers.org Metadata Resolution Service
#
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1
kind: Deployment
metadata:
    name: resolver
spec:
    selector:
        matchLabels:
            environment: production
            tier: api
            app: metadata
    replicas: 2
    template:
        metadata:
            labels:
                environment: production
                tier: api
                app: metadata
