# Kubernetes deployment description for Identifiers.org Resolver Web Service
#
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1
kind: Deployment
metadata:
    name: resolver
spec:
    selector:
        matchLabels:
            environment: production
            tier: api
            app: resolver
    replicas: 2
    
