# Definition of Redis backend service for Identifiers.org
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
# TODO - Remove this deployment, a cloud managed service will be used for this
apiVersion: v1
kind: Service
metadata:
    name: redis
    labels:
        environment: production
        tier: backend
        app: redis
spec:
    ports:
    - port: 6379
    selector:
        environment: production
        tier: backend
        app: redis
