# Managed Redis Endpoint for Google Cloud
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
kind: Endpoints
apiVersion: v1
metadata:
  name: redis
subsets:
  - addresses:
      - ip: 10.0.0.12
    ports:
      - port: 6379
